# Configurator
naoned_configurator:
    pattern:  /configurator
    defaults: { _controller: "NaonedDatabaseConfigBundle:Configurator:index" }
    options: { do_not_remove: true }

naoned_configurator_edit:
    pattern:  /configurator/{bundleName}
    defaults: { _controller: "NaonedDatabaseConfigBundle:Configurator:edit" }
    options: { do_not_remove: true }