# Configurator
Carlinhus_configurator:
    pattern:  /configurator
    defaults: { _controller: "CarlinhusDatabaseConfigBundle:Configurator:index" }
    options: { do_not_remove: true }

Carlinhus_configurator_edit:
    pattern:  /configurator/{bundleName}/{namespace}
    defaults:
      _controller: "CarlinhusDatabaseConfigBundle:Configurator:edit"
      namespace: ''
    options: { do_not_remove: true }