# Configurator
naoned_configurator:
    pattern:  /configurator
    defaults: { _controller: "NaonedDatabaseConfigBundle:Configurator:index" }
    options: { do_not_remove: true }

naoned_configurator_edit:
    pattern:  /configurator/{bundleName}/{namespace}
    defaults:
      _controller: "NaonedDatabaseConfigBundle:Configurator:edit"
      namespace: ''
    options: { do_not_remove: true }