# Configurator
unifik_configurator_edit:
    pattern:  /configurator/{configurationClass}/{namespace}
    defaults: { _controller: "UnifikDatabaseConfigBundle:Configurator:edit", namespace: '' }
    options: { do_not_remove: true }