services:
    naoned_database_config.repositories.extension:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - Naoned\DatabaseConfigBundle\Entity\Extension

    naoned_database_config.services.configuration:
        class: Naoned\DatabaseConfigBundle\Service\ConfigurationService
        arguments: [ "@kernel", "@naoned_database_config.repositories.extension", "@logger" ]