parameters:
    naoned_database_config.container_invalidator.class: Naoned\DatabaseConfigBundle\Lib\ContainerInvalidator

services:
    naoned_database_config.container_invalidator:
        class: %naoned_database_config.container_invalidator.class%
        arguments: [ '@kernel' ]
